### ISSUE TITLE
Improve styling of project metadata popup

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1010]
The current project metadata popup does not look good. It would be nice to improve the appearance of the table.
![image](https://user-images.githubusercontent.com/85183359/191909406-1dadf926-cc09-4a9d-8368-39773227af70.png)

**Comment by NevilleMthw** [comment]
Hi, Is there a way for me to get the popup to be displayed? I downloaded the application and then clicked on project metadata from the menu bar but nothing displays. Maybe I am doing it wrong?

**Comment by benedikt-richter** [comment]
Hi @NevilleMthw , 
the approach you are discribing seems correct. Just note that it is required to have opened an input file with the application (that contains project metadata to be displayed in the popup), before you open the popup. 
Try to open e.g. `example-files/opossum_input.json` and then click on the project metadata menu item.
