### ISSUE TITLE
Clean up project statistics popup

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1011]
After we introduce new graphs, tables and styling on project statistic popup it would be nice to finalize and clean up:
* check that styling is consistent
* check if there are any bugs or any things to improve
* refactor and clean up the code e.g. remove (or merge) duplicating styles...

**Comment by someshkhandelia** [comment]
@benedikt-richter gave a valuable suggestion:
We can have a separate table cell component for License Names, since they require different colors for criticality and are always for example left-aligned

**Comment by benedikt-richter** [comment]
In my opinion, it also would be an improvement to not display table header in ALL_CAPS. To me this looks a bit odd:

![Image](https://user-images.githubusercontent.com/46576389/192505835-2ec643ed-56ce-4db1-a60f-8bfd86aa47ae.png)
