### ISSUE TITLE
Improve license criticality shown in Project Statistics popup

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1051]
Currently we have no clear strategy of license criticality identification while deduplication for the project statistics popup, see function _getLicenseCriticality_ in the commit https://github.com/opossum-tool/OpossumUI/commit/e150967cb16b7195623e4bd50fd57b9d2715c231

The goal is to find a strategy, which will correctly highlight licenses and be clear for the user.

**Comment by mstykow** [comment]
Improved in #2233
