### ISSUE TITLE
Refactor CustomPieChart

### ISSUE THREAD

**Issue by leslielazzarino** [opossum-tool/OpossumUI#1078]
1. The component should be split into:
    a. a core component, with the same name, that just takes care of visualizing the data, 
    b. and logic taking care of different colors and other caracteristcs. 
2. The core component should become its own top-level component, with necessary tests. 
3. The color logic could be extracted either into a wrapper or multiple ones.

**Comment by someshkhandelia** [comment]
Regarding testing the new extracted component, please read comment: https://github.com/opossum-tool/OpossumUI/pull/1094#pullrequestreview-1164569332
