### ISSUE TITLE
Refactor project-statistics-popup-helpers.test.tsx

### ISSUE THREAD

**Issue by leslielazzarino** [opossum-tool/OpossumUI#1079]
1. One describe per function
2. One test for each expected behaviour, with precise description
    a. no duplicate tests with slightly different test data
3. Reference example: src/Frontend/Components/ResourcesList/__tests__/resource-list-helpers.test.ts

**Comment by benedikt-richter** [comment]
Currently the statistics popup tests are very fragile.
Consider improving on the tests e.g. by using aria labels for components and then to assert their presence instead of asserting their titles (and names of columns of tables).
