### ISSUE TITLE
Move ProjectStatisticsPopup tables top-level

### ISSUE THREAD

**Issue by leslielazzarino** [opossum-tool/OpossumUI#1080]
1. AttributionCountPerSourcePerLicenseTable
2. AttributionPropertyCountTable
3. CriticalLicensesTable
4. Split the helpers in 3 different files
5. Test each table thoroughly separately, test in the popup only that each sub component, table included, is present
6. Split the shared styles per component. When something is really shared move it to shared-styles

**Comment by benedikt-richter** [comment]
Furthermore, it would be great to extract common functionality of the individual tables. Possibly, there are some table cells with custom styling and logic that are shared between tables.
