### ISSUE TITLE
Improve dependency security

### ISSUE THREAD

**Issue by leslielazzarino** [opossum-tool/OpossumUI#1084]
1. Add yarn audit in the CI
2. Configure dependabot to wait some time, e.g. 30 days, before using an updated dependency on npm. That will give time to early adopters to find vulnerabilities.

**Comment by mstykow** [comment]
https://yarnpkg.com/package?name=yarn-audit-fix

**Comment by mstykow** [comment]
We already have renovate regularly updating the dependencies.
