### ISSUE TITLE
Improve styling of Pie Chart

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1092]
The styling of pie charts currently seems to be inconsistent with general the app.

In particular,
* the font is different from the one used thoughout the app,
* the tooltip looks different from the ones we typically use.

Possible further improvements:
* the white in the pie chart looks strange and should be replaced/removed,
* the colors used might be improved.

![Screenshot 2022-10-19 at 11 38 10](https://user-images.githubusercontent.com/46576389/196655615-ebbc3571-d3c6-4b85-bc39-381854896ed4.png)

**Comment by benedikt-richter** [comment]
Should be done after [#1078](https://github.com/opossum-tool/OpossumUI/issues/1078)

**Comment by someshkhandelia** [comment]
After the recent changes, it looks like this:

![image](https://user-images.githubusercontent.com/9270691/199539192-42be52ac-42f8-445a-a828-f8b90d1b2218.png)

The font of the legend cannot be changed. There is no way to specify it in the 3rd party API call.
