### ISSUE TITLE
Display differences between similar signals

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1175]
Currently, signals that share the same package name, package version, and copyright are displayed the same in the signals panel. This is also the case when there are actual differences between these signals (e.g. these might have different licenses).

The following screenshot illustrates the issue:
![Screenshot 2022-11-22 at 16 02 28](https://user-images.githubusercontent.com/46576389/203347864-7b30fd9a-9f1c-42aa-bbfb-0845b4107ada.png)

One possible solution to ease finding the relevant differences for the user is to collapse all of these cards and displaying a dropdown (or similar) that highlights the key differences.

**Comment by mstykow** [comment]
Not really clear how much of an issue the current behavior is. I can click through the individual cards to spot differences. Also see #2563.
