### ISSUE TITLE
Add filters in attribution and report views

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1216]
Currently there are only three filters in attribution and report views: only follow up, only/hide first party.
![image](https://user-images.githubusercontent.com/85183359/205332754-31d76e3c-5197-43bd-b0b4-304159efc1da.png)
 It would be nice to have more filters: only/hide preselected, only/hide incomplete attributions.

**Comment by vasily-pozdnyakov** [comment]
Make filters on attribution and report view similar to icons next to it: incomplete attributions, critical...

**Comment by benedikt-richter** [comment]
By now we added more filtering options. Therefore, I'd close this issue. 
Feel free to re-open if you consider some filter still missing.
