### ISSUE TITLE
Disable fetch data button if no url

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1217]
Fetch data button is still clickable and has tooltip if it is greyed out (e.g. when there is no url), compare to "open url" button next to it.
![image](https://user-images.githubusercontent.com/85183359/205334139-f2fb8fde-ec33-4421-97b0-254e88132b6f.png)

**Comment by benedikt-richter** [comment]
Good point! Actually, a tooltip could be shown for both. It can contain information why the respective action is not possible.
