### ISSUE TITLE
Inconsistent pre-selected icons in Report view

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1221]
Currently pre-selected icons in report view are inconsistent: blue letter "P" in attribution statistics on top and golden "P" next to actual attributions.
![image](https://user-images.githubusercontent.com/85183359/205341256-6ff0799c-efd7-4932-8f4f-2e9e9129a968.png)

**Comment by benedikt-richter** [comment]
There was the motivation to enable the user to quickly identify pre-selected, follow-up etc by using different colors for each. Here a solution could be to switch the colors of the edit icon and the pre-selected one. However, we have to be careful not to confuse the users to much by such a sudden change.
