### ISSUE TITLE
Improve style of the resources popup tree

### ISSUE THREAD

**Issue by lennartclaas** [opossum-tool/OpossumUI#1230]
The list in the resources popup was replaced with a tree. However, the tree's design is still rather sparse:
![resource_popup_tree_old](https://user-images.githubusercontent.com/83081698/205853617-6461515c-c16c-4ce5-9c1c-fc920c861be9.png)

The goal of this ticket is to develop and implement a meaningful icon style for the resources popup tree that hamonizes with the resources browser and does not lead to ambiguities.

**Comment by benedikt-richter** [comment]
contained in #1532
