### ISSUE TITLE
Add tests for workers

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1252]
Recently we had an issue with the TopProgressBar when open a new file (it was not updated, see fix https://github.com/opossum-tool/OpossumUI/commit/d7387027470a9ec979925183d29add67ac8f6699).
In order to early catch such bugs it would be nice to have tests for workers.
**Easy fix for that specific case:** add one more test for TopProgressBar, which covers the mentioned case.

**Comment by benedikt-richter** [comment]
Unfortunately, jest does not support web workers in tests. Therefore, closing this issue.
