### ISSUE TITLE
Hide "open resource in browser" tooltip

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1290]
The tooltip "open resource in browser" is still shown when the button is disabled.

![image](https://user-images.githubusercontent.com/85183359/209807060-5a593ead-67db-44dc-87b4-0e671fc40442.png)

**Comment by lennartclaas** [comment]
A possible solution could be to apply `props.sx` of the `IconButton` not only to the `MuiButtonBase` but also to the `MuiTooltip` component. Background: if the `IconButton` is to be hidden, it is usually done by `props.sx`.
