### ISSUE TITLE
Improve rendering time of package cards in attribution view

### ISSUE THREAD

**Issue by lennartclaas** [opossum-tool/OpossumUI#1312]
When scrolling through the list of package cards in the attribution view, the package cards are displayed with a large delay (it's a virtualized list). This behavior feels rather unpleasant and worsens user experience. 

The goal of this ticket is to identify the reason of the performance issue and to fix it, if possible.

The issue can be tested by loading `input_from_ort.json.gz`.

Example:
![Animation](https://user-images.githubusercontent.com/83081698/211573034-b1ce53fc-2c5d-4aec-ac2a-4dc6c8c355d2.gif)

**Comment by someshkhandelia** [comment]
From the following resources:
1. https://github.com/bvaughn/react-window
2. https://github.com/bvaughn/react-virtualized/issues/1327#issuecomment-463167513
3. https://web.dev/virtualize-long-lists-react-window/
4. https://stackoverflow.com/questions/43700938/react-virtualized-list-is-flickkering-lagging-when-scrolling

I gathered that a static `style` argument needs to be passed to the `row` of a `List`. Thus, I made the following change to test things:

### Previously
![image](https://user-images.githubusercontent.com/9270691/219047495-e979af76-451d-4d9b-8c47-5d61435ec943.png)

### What I tried (based on the internet suggestions)
![image](https://user-images.githubusercontent.com/9270691/219048020-1103415d-5cf7-4595-8288-03f795b2fa6d.png)


### Result: I could not get rid of the flickering issue by this method.
