### ISSUE TITLE
Errors in WebWorker

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1337]
There is an error logged in the console:

![image](https://user-images.githubusercontent.com/85183359/213400755-168cb176-742d-4bd5-bd81-ac29866a6d45.png)

### Reproduce:
* open big file "input_from_ort.json.gz" in the UI
* navigate through the resources tree and check the console log.

**Comment by mstykow** [comment]
Memory issues should be fixed as of #2398.
