### ISSUE TITLE
Show more info while loading file

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1395]
Currently, while loading a file a spinner is shown.

The goal of this ticket is to expose more information about what is currently happening to the user. This can be realized by exposing some of the electron backend logs to the user.

**Comment by vasily-pozdnyakov** [comment]
May be use a progress bar.

**Comment by benedikt-richter** [comment]
The difficulty, we are facing here, using a progress bar is that we do not know the current progress relative to the entire process. A statement, like progress equal 15%, is therefore difficult to make.

**Comment by benedikt-richter** [comment]
Closing as duplicate of https://github.com/opossum-tool/OpossumUI/issues/2323
