### ISSUE TITLE
Attribution wizard: Add copyright selection

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1455]
The goal of this issue is to extend the attribution wizard that was originally implemented in #1275.

In addition to the currently available fields, a way to select the copyright should be added.

As copyrights from signals typically are similar but still different and one might want to merge several copyrights, it would be good to allow the user to select multiple and also to edit the result manually in the attribution wizard.

**Comment by maxhbr** [comment]
additionally to selecting, it probably also needs the merge feature

**Comment by mstykow** [comment]
Wizard no longer exists.
