### ISSUE TITLE
Ignore "resolved" signals in attribution wizard

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1457]
Currently, the attribution wizard considers all signals that are attached to a file/flolder as well as all signals attached to the children of that resource.
Instead, the attribution wizard should ignore signals that are attached to resources with attributions and their children.

Possibly, we could have a checkbox that allows the user to configure the behavior (maybe later).

**Comment by mstykow** [comment]
Attribution wizard no longer exists.
