### ISSUE TITLE
Auto-update the app

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1472]
## Context

Currently user is completely responsible for Opossum app update - check for new releases on gitHub, manually download and install.

## Goal

Would be nice to add this functionality to the app.

## Ideas

1. Just check for updates and notify user about a new release every time starting the app. Might add a menu item "check for updates" or something similar.
2. (Probably later) Check for updates and automatically install it (after a user agreement)

**Comment by benedikt-richter** [comment]
This was fixed by #1529
