### ISSUE TITLE
Filter resource tree for unattributed files

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1479]
## Context

Currently there is no resource tree filtering. If the user wants to go through the unattributed files, he/she should click on the progress bar to move consecutively.

## Idea

It would be nice to introduce such filter, that the user can see the filtered tree with only unattributed resources and freely navigate through them.

## Note

The user might lose the context. Think about the ways to avoid that, e.g. by not hiding the resources at the same level (siblings).

**Comment by benedikt-richter** [comment]
Please, see related question in #1480.

**Comment by benedikt-richter** [comment]
Related to [#1454](https://github.com/opossum-tool/OpossumUI/issues/1454)

**Comment by vasily-pozdnyakov** [comment]
> Please, see related question in #1480.

Same here, corrected the description.

**Comment by benedikt-richter** [comment]
As disscussed losing context seems to make it not properly usable.
