### ISSUE TITLE
Filter resource tree by critical signals

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1480]
## Context

Currently there is no resource tree filtering. If the user wants to go through the resources with critical signals, he/she should click on the progress bar to move consecutively.

## Idea

It would be nice to introduce such filter, that the user can see the filtered tree with only resources with critical signals and freely navigate through them.

## Note

The user might lose the context. Think about the ways to avoid that, e.g. by not hiding the resources at the same level (siblings).
Ignore resolved signals?

**Comment by benedikt-richter** [comment]
What do you mean by "Locally deactivate the filter?"?

**Comment by benedikt-richter** [comment]
Related to [#1454](https://github.com/opossum-tool/OpossumUI/issues/1454)

**Comment by vasily-pozdnyakov** [comment]
> What do you mean by "Locally deactivate the filter?"?

Deleted that and clarified about context for the user.

**Comment by benedikt-richter** [comment]
This one is superceded by #1934
