### ISSUE TITLE
Add icons to the top bar menu items

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1500]
Currently there are no icons for the top bar menu sub-items:
![image](https://user-images.githubusercontent.com/85183359/226913018-2c608625-7778-47b0-a365-03240a715071.png)

It would be nice to add small icons before the items, e.g. open, save, export, undo, redo, zoom in, notices ...

**Comment by tarunsamanta2k20** [comment]
Please clarify the issue once. Is this task all about adding icons after file, edit, view, about help?

**Comment by vasily-pozdnyakov** [comment]
> Please clarify the issue once. Is this task all about adding icons after file, edit, view, about and help?
> 
> or before open file, save, export, project metadat....

Thanks for your comment. The issue is about icons before menu sub-items, e.g. open, save, export, etc. Also under the rest of the menu items, e.g. Undo, Redo, zoom in, notices...

**Comment by tarunsamanta2k20** [comment]
Okay then assign this issue to me.

**Comment by vasily-pozdnyakov** [comment]
@tarunsamanta2k20 Hi, are you still working on the issue or we can assign it to someone else?

**Comment by tarunsamanta2k20** [comment]
@vasily-pozdnyakov working on it.  Do you have any custom icons. Then please upload over here.

**Comment by tarunsamanta2k20** [comment]
@tarunsamanta2k20 see the below screenshots.

 
![image](https://github.com/opossum-tool/OpossumUI/assets/55488549/445a154e-6567-45a2-9a7a-9f2623c9b35f)


![image](https://github.com/opossum-tool/OpossumUI/assets/55488549/7f5429e7-65a3-4e14-a21c-8e32478feeb2)


![image](https://github.com/opossum-tool/OpossumUI/assets/55488549/9bb8f4be-9d55-4c07-8ba3-1b28aa071fcb)


![image](https://github.com/opossum-tool/OpossumUI/assets/55488549/d4374db5-7fd2-4ec3-9478-1d19a048d418)

![image](https://github.com/opossum-tool/OpossumUI/assets/55488549/2d7ef8ee-3547-4b4f-b949-19ba24ba8c49)


![image](https://github.com/opossum-tool/OpossumUI/assets/55488549/d77c4613-bd06-4d37-89b0-3f25a38b71c0)
