### ISSUE TITLE
Add breadcrumbs instead of path

### ISSUE THREAD

**Issue by leslielazzarino** [opossum-tool/OpossumUI#1501]
Should allow navigation. An icon next to them should still help by copying the full path.

**Comment by benedikt-richter** [comment]
Would be great to detail a bit more.
You suggest to replace the `PathBar` by a new component that works like breadcrumbs where each element is a folder name (except that last one that is the file name if it exists). 
Clicking on such a crumb should then navigate to the respective resource in the resource tree and open the attribution column?

**Comment by leslielazzarino** [comment]
Yes, that is what I thought. When vetting I found it really dofficult to navigate back to the parent folder when in a folder with tens of subfolders.

**Comment by benedikt-richter** [comment]
In addition, we should provide an icon to copy the path then.
Further, how to handle very long paths? The solution should mirror the existing one.

**Comment by benedikt-richter** [comment]
In attribution wizzard we still want to keep the PathBar as it is. Also note that we already use breadcrumbs there.
