### ISSUE TITLE
1st party flagged attributions should not be marked with dark orange color if package name is missing

### ISSUE THREAD

**Issue by lennartclaas** [opossum-tool/OpossumUI#1503]
In attribution view, attributions with missing package names are highlighted with dark orange color on the right side of the package card. The highlighting should be removed for 1st party attributions (indicated by the corresponding checkbox and the "1" icon on the package card).

Here, it is correctly highlighted (not 1st party).
![Screenshot 2023-03-23 111453](https://user-images.githubusercontent.com/83081698/227180704-8e8c3537-51a2-4478-aa1f-cae3af7286ba.png)

Here, the highlighting should be removed.
![Screenshot 2023-03-23 111514](https://user-images.githubusercontent.com/83081698/227180755-05a6f4ca-0cc2-4473-88f3-d8b0af1deee8.png)

**Comment by vasily-pozdnyakov** [comment]
I suppose the same holds for "Exclude from notice"
