### ISSUE TITLE
Vertical criticality indicator of package cards in attribution view unexpectedly vanishes

### ISSUE THREAD

**Issue by lennartclaas** [opossum-tool/OpossumUI#1510]
If the color of the triangular mark on the right of package cards in attribution view is changed, the vertical criticality indicator vanishes.

The triangular mark indicates missing package info. Dark orange for missing package name and light organge for other fields like version, URL, copyright, or license.

Initial situation (criticality indicator is visible)
![Screenshot 2023-03-27 133041](https://user-images.githubusercontent.com/83081698/227935421-801bb352-1e15-4a0d-a33e-efb0a2f33aa1.png)

URL added --> triangular mark vanished, as did the the criticality indicator (unwanted)
![Screenshot 2023-03-27 140158](https://user-images.githubusercontent.com/83081698/227937473-7bdebe19-5736-4b2a-94dc-87c70680611b.png)

URL removed again -->  triangular mark visible again, criticality indicator still gone
![Screenshot 2023-03-27 140229](https://user-images.githubusercontent.com/83081698/227937494-34beccf7-691e-4166-aa55-feb17c0c1807.png)

**Comment by vasily-pozdnyakov** [comment]
I also assume that when it fixed, it might be difficult to distinguish between darkOrange corner (incomplete package) and orange bar next to it (medium criticality).

**Comment by lennartclaas** [comment]
This is actually not bug but expected behavior. The vertical bar only appears for pre-selected attributions and is removed as soon these are confirmed or changed.
