### ISSUE TITLE
More information in the show linked resourses popup

### ISSUE THREAD

**Issue by leslielazzarino** [opossum-tool/OpossumUI#1532]
Currently it is an expanded, all-grey tree. It takes quite a bit of time and extra effort to undestand where the signal is actually linked. It would be helpful if the resources where the signal is actually linked would be highlighted. That would help to understand the picture with a quick glance. In general also the usual icon color-coding from the main tree could sometimes be useful.

**Comment by mstykow** [comment]
Popup has been deleted as of #2570.
