### ISSUE TITLE
Comments not reaching the bottom of the UI

### ISSUE THREAD

**Issue by MarkusObendrauf** [opossum-tool/OpossumUI#1559]
The comment box does not reach the bottom of the window. Instead, there is some empty space between the box and the bottom of the UI.

![image](https://user-images.githubusercontent.com/107913663/231192686-5f5a6e82-ccfb-47cb-bac3-642a8feb5601.png)
![image](https://user-images.githubusercontent.com/107913663/231192790-610339c2-fb42-4894-a16a-894ad58c6957.png)

Expected behaviour: The comments box reaches the bottom of the screen, like the other text boxes:
![image](https://user-images.githubusercontent.com/107913663/231193036-f8be5e10-0e22-4974-a316-130fdad2e717.png)

**Comment by mstykow** [comment]
#2357
