### ISSUE TITLE
Revise comment stack

### ISSUE THREAD

**Issue by lennartclaas** [opossum-tool/OpossumUI#1572]
The goal of this ticket is twofold:
- remove whitespace before and after a comment (signals only, not for (pre-selected) attributions)
- adjust the styling such that wrapping a long line does not introduce a second scroll bar

Screenshot that shows the issues that should be fixed:
![Screenshot 2023-04-13 092242](https://user-images.githubusercontent.com/83081698/231685300-8a111386-31cf-434a-821f-ee765d3361d8.png)

It is reasonable to fix this issue together with #1559.

**Comment by mstykow** [comment]
#2357

**Comment by mstykow** [comment]
#2357
