### ISSUE TITLE
Surface in "signals in folder content" which signals are covered by an attribution

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1573]
**Is your feature request related to a problem? Please describe.**
As an OpossumUI user, working on a folder with 100 subfolders containing packages. When e.g. 40% are done and in the signals in folder content of the top level folder view the user notices that some complex signals are contained, they have no idea if the 40% clearing already covers all the complex signals without clicking on each folders one by one. 

**Describe the solution you'd like**
I think we somehow need to surface for "signals in folder content", which of them are covered by an attribution and which are not yet "green".

**Comment by benedikt-richter** [comment]
Also see related issue: #982

**Comment by mstykow** [comment]
@benedikt-richter I'm not understanding the issue description. Perhaps you can reword the whole issue.
Also note that the folder progress bar no longer exists as of #2570.
