### ISSUE TITLE
Opossum Integration

### ISSUE THREAD

**Issue by jon-livingstone** [opossum-tool/OpossumUI#1582]
I am looking to integrate Opossum into my DevOps process.
Do you have any documentation that can walk me through the best practices for integrating Opossum into something like TerraForm?

**Comment by benedikt-richter** [comment]
I'm not sure, I completely understand the use case.

Can you provide some more context?

**Comment by jon-livingstone** [comment]
Sure. I am trying to find a software composition analysis tool that enables open-source security and license compliance, allowing for rapid development while remaining secure. (especially with the rise of AI-assisted coding)
I'm looking for an open-source tool that has some of the same scanning abilities as Black Duck's or Synk's.

My particular use case: I am trying to integrate the Opossum tool into a Terraform-built Docker container. 
(Terraform/Docker Tutorial - https://developer.hashicorp.com/terraform/tutorials/docker-get-started)

**Comment by benedikt-richter** [comment]
I see. OpossumUI does not contain any scanners that do software composition analysis, like e.g. ScanCode. Instead OpossumUI is a desktop app that allows to open the findings of various different scanners.

The typical workflow to start with OpossumUI is to 
* run one or several software composition analysis tools/scanners
* create a input file for OpossumUI (e.g. using https://github.com/opossum-tool/opossum.lib.hs)
* open that file in OpossumUI to audit and inventory codebases 

Therefore, as your use case is automatic scanning of code and probably alerting in case of "unwanted" licenses, if I understand correctly, and might not include a manual audit part, OpossumUI might be not well suited.

Do I understand correctly that you are looking for an automatic tool without manual work (for e.g. auditing results)?

**Comment by benedikt-richter** [comment]
@jon-livingstone 
Currently, there are no plans for an automatic scanning version.

So far OpossumUI is designed as a scanner/inpurt generator agnositc tool that can integrate with many OSS scanners.
