### ISSUE TITLE
Invalid link to file formats inside README

### ISSUE THREAD

**Issue by stefan6419846** [opossum-tool/OpossumUI#1596]
The README references the contribution guide for the file formats documentation: https://github.com/opossum-tool/OpossumUI/blob/b02bfeb542f185adc6b2f1bf39a51151742e82c7/README.md?plain=1#L81

This does not hold true any more as https://github.com/opossum-tool/OpossumUI/commit/4be1b8d55b24c84655171f53e0f330b8d0071edc moved the corresponding section to the README itself. (I would have opened a PR for this directly, but I do not want to expose my name as required by the DCO.)

**Comment by benedikt-richter** [comment]
Thanks for pointing that out!
