### ISSUE TITLE
Enable source maps in Vite

### ISSUE THREAD

**Issue by lennartclaas** [opossum-tool/OpossumUI#1682]
By changing to Vite, we lost the feature of debugging files in the developer tools. It seems that no source maps are created with the current Vite settings.

The goal of this ticket is to enable source maps in Vite settings.

**Comment by mstykow** [comment]
I'm not understanding the issue. When I switch to the "sources" tab I can see files and use debugging as usual. Please explain what you're missing. @lennartclaas 

![Image](https://github.com/opossum-tool/OpossumUI/assets/46091730/e684b32b-ccea-493d-881d-914e55f70532)

**Comment by lennartclaas** [comment]
Ah, that's nice. I guess the feature was added in the meanwhile.
