### ISSUE TITLE
Menu bar icons are not visible in light mode

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1684]
## Context
In #1674 top bar menu icons were introduced.

## Issue
The icons look fine on MacOs, however they are not visible in light mode on Windows:
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/c807cb43-ff0c-4ad7-ac35-a70de867cb51)

## Ideas
This can be fixed by:
* Find icons with a good color which will work fine on different systems and in dark/light mode
* OR add dark icons to use in light mode and write a logic to decide which icons set to use.

**Comment by tarunsamanta2k20** [comment]
@vasily-pozdnyakov let me check. May I ask you some questions?

**Comment by tarunsamanta2k20** [comment]
@vasily-pozdnyakov i don't have windows install. Could you please let me know if this default is on Windows?

**Comment by tarunsamanta2k20** [comment]
If you enable dark mode in windows. Then how is it looking?

**Comment by tarunsamanta2k20** [comment]
@vasily-pozdnyakov should I use black Icons over?

**Comment by tarunsamanta2k20** [comment]
Those will gets visible in both white and dark mode.

**Comment by vasily-pozdnyakov** [comment]
> @vasily-pozdnyakov should I use black Icons over?

please check if it works fine on different systems (if you can) and also in dark/light mode.

**Comment by tarunsamanta2k20** [comment]
> > @vasily-pozdnyakov should I use black Icons over?
> 
> please check if it works fine on different systems (if you can) and also in dark/light mode. You can also create a pull request with proposed icons and we also test it.

@vasily-pozdnyakov if I use black icons it will be looking good on light mode, but won't look good on dark mode.

**Comment by tarunsamanta2k20** [comment]
But will be visible on both mode.

**Comment by tarunsamanta2k20** [comment]
@vasily-pozdnyakov see the above images.

**Comment by tarunsamanta2k20** [comment]
@vasily-pozdnyakov Mui icons are only available in white and black color. One more thing is electron js doesn't supports React like icons, then I could at least change the color of icons. 

I can use two sets of icons, no problem with that but discuss with @benedikt-richter . Because after changes he may not accept.

**Comment by tarunsamanta2k20** [comment]
@vasily-pozdnyakov let me know asap

**Comment by benedikt-richter** [comment]
@tarunsamanta2k20 Personally, I like the idea of having both black and white icons, depending on the user's settings regarding dark mode.

**Comment by tarunsamanta2k20** [comment]
@benedikt-richter well. It will work. The user must reopen the application if he/she changes the mode while the application is running.

**Comment by benedikt-richter** [comment]
> @benedikt-richter well. It will work. The user must reopen the application if he/she changes the mode while the application is running.

That's true. However, I think that should be acceptable, as the user most likely won't switch between modes very frequently.
