### ISSUE TITLE
Resources icon remains green after deleting attributions

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1685]
## Context
User can create and delete attributions for resources. Unattributed resources have grey icons, attributed - dark green. 

## Issue
After creating and deleting all attributions for a resource the icon remains light green.
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/2ce0b4ae-9464-401f-a8b8-5058ff706109)

The light green color is actually used in Progress Bar for 'Files with only pre-selected attributions'. This is confusing.
One should check if it is an intended behaviour and fix it if not.

**Comment by benedikt-richter** [comment]
This is not an intended bahavior. 
When adding an attribution to a resource and subsequently removing it, the state of the icon should be the same as before.
