### ISSUE TITLE
'1st party' and 'Needs Review' checkboxes can create empty attributions

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1686]
## Context
Detailed attribution info column has a number of checkboxes. They actually work differently with empty attributions.

## Issue
Creation of an empty attribution with selected 'Follow-up' or 'Exclude from Notice' is not allowed.
However, for '1st Party' and 'Needs Review' it is possible to create an empty attribution.
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/ab7f6af1-04c0-48a0-a1ce-c4ff4c526962)

**Note**: in case of 'Needs Review' the attribution is completely empty. In case of '1st Party' it is empty, but the attribution card has a title 'First Party'
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/084dd2d9-4f91-41c5-990d-8269069548a3)

One need to figure out if it is an intended behavior and fix it is necessary.

**Comment by benedikt-richter** [comment]
Having an attribution that has "just the first party flag ticked" is a feature we want to support and do currently support.
However, for having an attribution with no comment and "just the needs review flag ticked" I see no proper use case. Would be good to handle these attributions like the other ones (only exclude from notice ticked, for example).
