### ISSUE TITLE
Improve PURL handling in attribution wizzard

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1865]
Currently, in the attribution viewer, there are two points related to the namespace and the type inside of the PURL of a package that are inconvenient for the user to handle:
* When selecting a namespace, as a user, I do not see which package names correspond to that namespace. This should be made explicit.
* It is not possible to set the type. Either the attribution one starts with already has a type and this type is taken for the PURL with no way to modify or the type "generic" is chosen. Instead, the user should be able to modify the type.

**Comment by mstykow** [comment]
Wizard got deleted.
