### ISSUE TITLE
Try https://www.npmjs.com/package/adm-zip as zipping library

### ISSUE THREAD

**Issue by leslielazzarino** [opossum-tool/OpossumUI#1893]
It should provide the following advantages, as the .opossum file would updated in memory:
- faster saving time, as the input file does not need to be compressed any longer,
- smaller memory footprint in the backend, as the input (+output) file is stored compressed.

The library should be tried and it should be checked that these expected advantages are actually realized. If yes, and everything else stays more or less the same, this library should be used instead of the current one.

**Comment by maxhbr** [comment]
the goal is to do the following?

```js
var zip = new AdmZip();
zip.addFile("input.json", Buffer.from(input_json, "utf8"), "");

zip.addFile("output.json", Buffer.from(initial_output_json, "utf8"), "");
zip.writeZip(opossum_file_path);

// ... 
// using the same zip handle and overwrite output.json and write it to the FS
zip.addFile("output.json", Buffer.from(updated_output_json, "utf8"), "");
zip.writeZip(opossum_file_path);

// ...
zip.addFile("output.json", Buffer.from(even_newer_output_json, "utf8"), "");
zip.writeZip(opossum_file_path);
```

**Comment by maxhbr** [comment]
that should be possible to just test very lightweight. Just collect a few states of output JSON and write them in a loop to some zip and measure the impact?

**Comment by mstykow** [comment]
We don't have a problem with the speed at which zipping occurs in the backend.
