### ISSUE TITLE
Introduce "Locate Popup"

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1934]
**Goal**
Introduce a new popup that enables the user to locate signals in the resource tree.
For this reason, we want to introduce a new popup that allows to configure criteria for signals. When the user configures a set of cirteria and clicks "apply", the resources that have attached signals that match these criteria are highlighted in the resource tree.

The visuals as well as some additional details are described in the following mock:

![Untitled scene](https://github.com/opossum-tool/OpossumUI/assets/46576389/79793609-f242-4721-86fa-7198ac19ff12)

A first implementation is provided by #1935

**Comment by mstykow** [comment]
This is completed.
