### ISSUE TITLE
[1935] Calculate tree nodes that are highlighted

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1944]
Calculate tree nodes that are highlighted:

* Input: criticality, license name (in future first party,...)
* Loop over attributions to filter for relevant ones
  * If the searched license matches either the short name or full name of a frequent license, both names should be found 
* Use attributionToResources to find relevant resources
* Use resources to calculate ResourcesWithAttributedChildren
  * We already calculate ResourcesWithAttributedChildren in quite some other places
* Update state on hitting apply or reset

--
Part of  #1935

**Comment by antonbauhofer** [comment]
just fyi, in getAttributionDataFromSetAttributionDataPayload, we do the computation "the other way round" and compute the children with attributions. I still think it is probably better, though, to start from the located  resources and compute the parents for those.
