### ISSUE TITLE
[1935] Finalize styling

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1968]
The goal of this ticket is to finalize styling of the new popup to be consistent with the rest of the app.

--
Part of https://github.com/opossum-tool/OpossumUI/issues/1935

**Comment by vasily-pozdnyakov** [comment]
two issues:
- Apply button should be highlighted by default, like here 
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/fe3522d4-f4c9-4b98-a4f6-bb7216d073b9)

- fix "filter is on" icon being above scroll bar, see 
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/937eee9d-2632-4035-a61e-2b6fb6170a0c)
