### ISSUE TITLE
[1987] Extend PackageInfo and schema

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1988]
Extend `PackageInfo` and schema by adding the following fields (here example data is shown):

```
"preferredOverOriginIds": [
 "1eb75f3b-fc84-e781-ad9d-d46d6d61a668"
],
"preferred": true,

```

--
Part of #1987

**Comment by davidmundelius** [comment]
I am currently working on this. I cannot assign myself as I am not a collaborator of this project.
