### ISSUE TITLE
[1987] Avoid accidental marking of attributions as preferred

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1993]
When an attribution is marked as preferred and it is linked to at least two resources then it should be unlinked from the respective resource and a copy is created that is marked as preferred.
This avoids that the user implicitly marks attributions as preferred.

--
Part of #1987

**Comment by leslielazzarino** [comment]
Alredy implemented when global saving of prefered attributions has been added.
