### ISSUE TITLE
Error for some licenses

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#2021]
Open example.opossum and try to locate the license "MIT " (the last one in the list, with empty space at the end) with the new Locate Popup
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/c3709d13-a150-49e4-8dd6-5ecbb096701f)

Not sure what is the problem: example file is corrupted or there is an actual bug in the code.

Related to https://github.com/opossum-tool/OpossumUI/issues/1935

**Comment by benedikt-richter** [comment]
Suggestion: 
* do not write signals without resources into the redux state.
This would solve the issue and avoid running into the same issue at other places.
