### ISSUE TITLE
Handle slow "add to resource" action

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#2061]
**Describe the bug**
When a user adds an attribution to a resource in the case of huge input files (with several 100k resources and signals), the UI "freezes" for a couple of seconds, while the user can still click the "+" icon to add furhter attributions. The waiting time can accumulate and the UI seems frozen.

**To Reproduce**

1. Open a huge opossum file
2. Navigate to. the root folder on click it
3. Add an attribution by clicking "+" icon (see screenshot)
4. Observe that UI is frozen for a few seconds and during that time repeat clicking on the "+" icon
5. Observe that the UI is frozen for an even longer time if "+" icon clicked repeatedly

![Screenshot 2024-01-12 at 14 47 46](https://github.com/opossum-tool/OpossumUI/assets/46576389/b60aa79c-06d0-4957-b1fa-9bf8d01b92e6)

**Expected behavior**
To avoid this, we want to disable user interactions while a "save" process is running.

Possible options:
* disable "+" icon until saving is finished
* add spinner instead of "+" icon

**Additional context**
related to #1919

**Comment by benedikt-richter** [comment]
Related issue: #2460

**Comment by mstykow** [comment]
As of #2570 it is no longer possible to repeatedly click the "+" button. The time it takes to add an attribution may still be in the ballpark of 2 seconds but this seems acceptable.
