### ISSUE TITLE
Improve test suite

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#2153]
The goal of this ticket is to further improve the performace of our test suite.

There are some measures that should be considered:
* deduplicate tests that separately test the same feature
* replace slow tests by faster ones
  * e.g. test features using unit tests instead of integration tests where it brings advantage
*  remove unnecessary tests

related ticket: #2151

**Comment by mstykow** [comment]
Was completed by replacing int by e2e tests.
