### ISSUE TITLE
Colors on progress and criticality bar are inconsistent

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#2282]
**Is your feature request related to a problem? Please describe.**
The colors on progress and criticality bars are inconsistent, e.g. criticality bar does not show any files with only non-critical signals, however progress bar shows them with red color. In addition, criticality pie chart on project statistics popup shows such signals with dark blue color.

**Describe the solution you'd like**
Make colors for different files and signals consistent within the app. e.g. non-critical signals = dark blue.

**Additional context**
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/0b2cdc9a-3bb2-447f-99ae-bd848acb4e37)

**Comment by meretp** [comment]
Closing this as the benefit for the user is not clear.
