### ISSUE TITLE
Figure out behavior of color scheme of resource browser

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#2284]
**Describe the bug**
The behavior of colors at the resource browser is unclear sometimes, e.g. a folder with no attributions but with children with signals is red (ok), once you add an attribution to the folder it becomes green (ok), however, after deletion of the attribution is becomes blue (but expected to be red again).
Note: after reopening the file the colors are fine again.

**To Reproduce**

1. Open any example file
2. find a folder with no attributions but with children with signals (it should be red)
3. create an attribution for the folder (it will become green)
4. delete the attribution (the folder becomes blue instead of red)

**Expected behavior**
The color should come to the initial state.

**Screenshots**
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/e2c25f58-af8d-4606-8fb2-fa13890f646a)
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/9c386b3c-3429-4ea2-adff-3b3d4edbba07)
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/cf5407a6-2f1a-4904-84c6-df854a318a75)

**Desktop (please complete the following information):**

- OS: Windows

**Comment by mstykow** [comment]
Fixed in #2570
