### ISSUE TITLE
Improve file processing state

### ISSUE THREAD

**Issue by mstykow** [opossum-tool/OpossumUI#2323]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to see more context while an file is being opened/exported instead of a simple loading spinner.

**Describe the solution you'd like**
Display a dialog describing concrete steps that are performed by the backend when a file is processed.
Show which steps are completed and which steps are still in progress.
If possible, show a linear progress indicator.

**Comment by benedikt-richter** [comment]
This probably replaces #1395
