### ISSUE TITLE
Show original source for attributions

### ISSUE THREAD

**Issue by meretp** [opossum-tool/OpossumUI#2327]
**Is your feature request related to a problem? Please describe.**
Currently the user is not able to understand where an attribution is coming from.

**Describe the solution you'd like**
- Create a map "originID -> signal" 
- Create a function to look up the original source of an attribution by looking up the corresponding signal using the originId. and display it in the source TextField which is already used for signals.

**Describe alternatives you've considered**
An alternative would be to display an additional text instead of using the Source TextField.

**Comment by mstykow** [comment]
Completed in #2424
