### ISSUE TITLE
make preferred status visible immediatly

### ISSUE THREAD

**Issue by alexzurbonsen** [opossum-tool/OpossumUI#2330]
**Is your feature request related to a problem? Please describe.**
Currently, if a user marks an attribution as preferred, the golden star, that visualizes this choice, is only shown after the change is saved. Analogously for an attribution that is unmarked as preferred.

**Describe the solution you'd like**
It would be great to get visual feedback immediatly after the "Mark/Unmark as preferred" button is pressed in the hamburger/context menu, not only after the change is saved.

**Describe alternatives you've considered**
None.

**Comment by mstykow** [comment]
This is done now because of the auditing option chips which immediately reflect changes to preferred/wasPreferred.
