### ISSUE TITLE
Add package name suggestions for packages (via deps.dev)

### ISSUE THREAD

**Issue by mstykow** [opossum-tool/OpossumUI#2394]
- use this endpoint to load suggestions based on query string: https://deps.dev/_/search/suggest?q=react
- note: this always returns at most 10 results which include package name and package type
- ignore any projects for now (deps.dev distinguishes between packages and projects, where projects are GitHub, GitLab, Bitbucket)
- ignore version and license name for now
- add the suggestions coming from deps.dev to the end of the autocomplete suggestions
- to handle the loading state, use a simple skeleton placeholder for three search results based on the existing suggestion card
- if an error occurs during the network request, just return an empty array of results

**Comment by davidmundelius** [comment]
Will split this in three PRs:

- [ ] Bypass CORS policy in backend
- [ ] Set up react query hook for loading suggestions based on search term
- [ ] Show suggestions or loading state
