### ISSUE TITLE
Remember scroll position in attribution view 

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#2399]
**Is your feature request related to a problem? Please describe.**
Current behavior:
* If on attribution view
* navigating to audit view
* and back it is difficult to find past attribution (scroll position)

**Describe the solution you'd like**
The attribution that was selected on attribution view should be remembered and there should be auto-scrolling to that attribution in list of attributions to center it (if it still does exist).

**Describe alternatives you've considered**
None

**Comment by mstykow** [comment]
Use the `indexToScrollTo` prop of the `List` component to scroll to the selected attribution which you can look up in the list of all attributions passed to the list by ID.
