### ISSUE TITLE
Improve workflow for QA work including preferred attributions

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#2401]
**Is your feature request related to a problem? Please describe.**
The following aspects of the QA process should be improved:
* During the QA process, it is currently difficult to get the set of attributions that was preferred initially and then was modified such that the "was preferred" attribute is gone
* There is no way to suggest changes to attributions with the "was preferred" attribute that can be taken into account by the QA team

**Describe the solution you'd like**
Requirements:
* it is possible to view all attributions that were preferred and got modified or attributions that are preferred but got modified
* changes to these attributions can be reviewed in direct comparison to the values from the original attribution 
* the changes can then be either accepted or discarded

From the user perspective:
* It is possible to modify attributions with "was preferred". 
* When modifing the attribution for the first time the following warning is shown to the user: 
![Screenshot 2024-01-05 133235](https://github.com/opossum-tool/OpossumUI/assets/89708272/844fb235-06e6-44d2-916c-a0b070de8993)
* After acknowledging the warning the user can modify the attribution and confirm his changes as for any regular attribution. 
* After the changes were saved the attribution is marked with a crossed out 'was_preferred' star .

From the QA user perspective (in QA mode):
* In attribution view it should be possible to filter for attributions that were preferred or attributions that are preferred but got modified by a user not in QA mode:
![Modified previously preffered](https://github.com/opossum-tool/OpossumUI/assets/89708272/9d1c2805-5c8e-4d6c-ac3f-3209837896d5)
* Selecting one of these attributions, the user should be able to see what was changed relative to the original attribution:
![Screenshot 2024-01-05 154259 - Kopie](https://github.com/opossum-tool/OpossumUI/assets/89708272/bcbafb64-7a51-4b07-ad5b-52d759a00964)
* The QA user can either confirm or discard the changes:
![Screenshot 2024-01-05 155151](https://github.com/opossum-tool/OpossumUI/assets/89708272/1441a7d7-7f5d-42b8-ac58-7d9d0658eb65)

**Describe alternatives you've considered**
tbd

**Comment by FlorianSchepers** [comment]
This Issue will be closed as it its features were either implemented by https://github.com/opossum-tool/OpossumUI/pull/2474 or are tracked by https://github.com/opossum-tool/OpossumUI/issues/2488.

**Comment by FlorianSchepers** [comment]
see above comment

**Comment by FlorianSchepers** [comment]
This Issue will be closed as it its features were either implemented by https://github.com/opossum-tool/OpossumUI/pull/2474 or are tracked by https://github.com/opossum-tool/OpossumUI/issues/2488.

**Comment by FlorianSchepers** [comment]
This Issue will be closed as it its features were either implemented by https://github.com/opossum-tool/OpossumUI/pull/2474 or are tracked by https://github.com/opossum-tool/OpossumUI/issues/2488.
