### ISSUE TITLE
Top bar menu enabled even when no project is opened

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#2411]
**Describe the bug**
Right after opening of the app (before opening any project) the top bar menu is enabled and user can choose any option. Some of them are fine (qa mode), some of them do nothing (Project metadata or project statistics) and some of them result in error (file->export)

**To Reproduce**
Start opossumUI and try the menu items.

**Expected behavior**
Some options should be disabled.

**Screenshots**
![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/e8692e9c-ec55-44b8-9c69-b3254600dd80)

![image](https://github.com/opossum-tool/OpossumUI/assets/85183359/21398bf8-aa3e-46e3-93b7-859bb4d5a21f)

**Comment by mstykow** [comment]
https://stackoverflow.com/questions/47756822/change-electrons-menu-items-status-dynamically
