### ISSUE TITLE
Handle prefer globally in report view

### ISSUE THREAD

**Issue by alexzurbonsen** [opossum-tool/OpossumUI#2414]
**Is your feature request related to a problem? Please describe.**
In #2332 we also enable preferring an attribution, and thus also preferring it globally. But the warning popup that we show in audit and attribution view is not wired into report view yet.

**Describe the solution you'd like**
We should either:
- wire the warning popup for preferring globally in report view
- or consider if we need the edit attribution popup in report view. We could also delete it and instead redirect the user to the attribution view if she clicks the edit button in report view.

**Comment by mstykow** [comment]
Maybe also a candidate to do this logic with the new confirmation dialog introduced in #2433 .
