### ISSUE TITLE
Add option to reset attribution content to content of original signal 

### ISSUE THREAD

**Issue by FlorianSchepers** [opossum-tool/OpossumUI#2475]
**Is your feature request related to a problem? Please describe.**
- In case an attribution is generated from a signal, modified and the changes are saved, there is no streight forward way to figure out which changes have been made to the attribution in hindsight.

**Describe the solution you'd like**
Enable the user to revert all changes made to the attribution from the point when it was initially generated from the signal  

Implementation
- Change the the `Revert` button into a drop down menue with the two options: `Revert latest changes` and `Revert to original values` (??).
![Menue_new](https://github.com/opossum-tool/OpossumUI/assets/89708272/d99c208f-d621-479e-a79e-40434d65fe5f)

- When selecting `Revert latest changes` it behaves like the current `Revert` button and just reverts all unsaved changes.
- When selecting `Revert to original values` it resets all fields of the attribution to the values of the signal linked via the origin id. 
- In case an attribution has no origin id the option `Revert to original values` is dissabled.

Additional points
- Make sure that for attributions with the chip `modified previously preffered` the chip is changed back to `previously preffered` (i.e. the state should be back to `was_preferred`).  
- The reset button in the chip `modified previously preffered` is no longer required an can be removed.

**Describe alternatives you've considered**
- Adding a diff view that shows the values of the origianl signals additionaly to its current values in the fields of the attribution. We decided against this option as it would cause a bad ux when the content of the fields becomes to large. 

**Additional context**
This Issue is a follow up from https://github.com/opossum-tool/OpossumUI/issues/2401

**Comment by mstykow** [comment]
Done in #2488
