### ISSUE TITLE
Activate immutability redux check in the CI

### ISSUE THREAD

**Issue by leslielazzarino** [opossum-tool/OpossumUI#2493]
**Is your feature request related to a problem? Please describe.**
The serializable and immutable checks are important, but if they need to be performed manually they might be forgotten.

**Describe the solution you'd like**
We could setthe parameters *serializableCheck* and *immutableCheck* in *src/Frontend/state/configure-store.ts* through environment variables. That would allow to use different values locally or in the CI.

**Describe alternatives you've considered**
src/Frontend/state/configure-store.ts could have a different version, that replaces the regular one in the CI.

**Comment by mstykow** [comment]
Cannot activate the serializability check yet because the tech debt has not been resolved there yet.
