### ISSUE TITLE
Disable package namespace field in case the package type does not support namespaces

### ISSUE THREAD

**Issue by FlorianSchepers** [opossum-tool/OpossumUI#2496]
**Is your feature request related to a problem? Please describe.**
Some package types, e.g., npm, do not support namespaces. Thus, the user should be prevented from specifying a namespace in these cases as it would be wrong information.

**Describe the solution you'd like**
Disable the package namespace field for attributions with package types that do not support package namespaces.

**Comment by mstykow** [comment]
Won't do this for now because package name is optional even for types which don't require it: https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst
