### ISSUE TITLE
Show hidden attributions

### ISSUE THREAD

**Issue by antonbauhofer** [opossum-tool/OpossumUI#2511]
**Is your feature request related to a problem? Please describe.**
Currently, when hiding a signal that is shown in the section "Signals in Folder Content", there is no easy way of finding that attribution again.

**Describe the solution you'd like**
One option to make such hidden signals more accessible would be to add an option under the top bar item "view" to show hidden signals.

**Comment by mstykow** [comment]
This has been addressed in OpossumUI 2.0 by introducing a toggle button to show/hide deleted signals.
