### ISSUE TITLE
Race conditions for in folder content

### ISSUE THREAD

**Issue by leslielazzarino** [opossum-tool/OpossumUI#2556]
**Describe the bug**
In the resource tree, when on a folder and navigating on another, the synchronous parts of the central and left column change pretty fast. While the calculation of "Signals in Folder Content" is ongoing, the results for previous folder are still shown. If a third folder is clicked upon while going from the first one to the last, e.g. by mistake, the results for this intermediate click are also shown before the final one. The behavior is confusing, as sometimes you are not sure if what you are seeing is relevant or not yet.

**To Reproduce**

1. Open an OpossumUI file, with 10ks of signals
2. Click on a top-level folder (one level below root)
3. Wait for everything async to load
4. Click on the top level folder
5.  See that the old "... in Folder Content" are still shown for a bit.

**Expected behavior**
When clicking on a new resource, a glimmer is shown in place of the "signal in folder content" and of the "attributions in folder content", until the results relative to the selected resource replace them.

**Comment by mstykow** [comment]
This is no longer a problem with OpossumUI 2.0 because there a loading state covers the "old" signals.
