### ISSUE TITLE
Pressing "cmd+s" on an already saved/confirmed attribution delets the attribution 

### ISSUE THREAD

**Issue by FlorianSchepers** [opossum-tool/OpossumUI#2586]
**Describe the bug**
It seems the shortcut "cmd+s", typically used to save or confirm attributions, is not disable for already saved / confirmed attributions. Instead it will delete the attribution.

**To Reproduce**

1. Go to an attribution that is already saved / confirmed
2. Press "cmd+s" 
3. See that the corresponding attribution is deleted

**Expected behavior**
The shortkey "cmd+s" is disabled for already saved / confirmed attributions.

**Additional context**
This Bug was reported for OpossumUI 2.0.

**Comment by mstykow** [comment]
Fixed as review comment on #2570
