### ISSUE TITLE
Reintroduce "cmd+f" shortcut for quick search of resources

### ISSUE THREAD

**Issue by FlorianSchepers** [opossum-tool/OpossumUI#2587]
**Is your feature request related to a problem? Please describe.**
In previous version of OpossumUI the user had the option to use the shortcut "cmd+f" to open the search for resources. With the update to OpossumUI 2.0 this feature was removed. It would be helpful to bring the feature back.

**Describe the solution you'd like**
Reintroduce the shortcut "cmd+f". When executed the resource search should be opened.

**Describe alternatives you've considered**
It was considered to open either the resoruce, attribution or signal search when "cmd+f" is pressed, dependeing on which element was selected most recently, i.e., a resource, an attribution or a signal, respectively. We decided against this option as it would makes to shortcut functionallity more complex and might lead to confusion by the user. 

**Additional context**
This is a feature request for OpossumUI 2.0

**Comment by mstykow** [comment]
Two ideas:
1. cmd+f only searches the items in the currently focused list. so if i'm looking at an attribution, it would search the attributions etc.
2. introduce one search shortcut for each list.
