### ISSUE TITLE
Automatically map license names to SPDX license identifiers

### ISSUE THREAD

**Issue by FlorianSchepers** [opossum-tool/OpossumUI#2588]
**Is your feature request related to a problem? Please describe.**
When selecting a common license for an attribution from the dropdown menue the full name will be shown in the "license name" field. However, we want that the SPDX license identifier is shown instead.

**Describe the solution you'd like**
Automatically map the license names of the common licenses to the corresponding SPDX license identifiers when selecting them from the dropdown menue.

**Additional context**
This is a feature request for OpossumUI 2.0

**Comment by mstykow** [comment]
Won't do for now.
