### ISSUE TITLE
Correct ORT repository reference in README

### ISSUE THREAD

**Issue by ja-he** [opossum-tool/OpossumUI#382]
There are multiple references to the ORT fork `opossum-tool/oss-review-toolkit` in the README.
As this fork is not accessible, and as ORT itself notes support for OpossumUI, I assume this is out of date information and the reference should instead be to `oss-review-toolkit/ort`?

Locations where this reference occurs:
- the graphic under [integration](https://github.com/opossum-tool/OpossumUI#integration-in-the-ecosystem)
- the section [generating-input-files](https://github.com/opossum-tool/OpossumUI#generating-input-files)

Apologies if I'm misreading (or if the issue is considered noise, I could not find an issue template).

**Comment by maxhbr** [comment]
good point, this fork is no longer existent and upstream merged all change requests. We will fix it, thank you for that hint.
