### ISSUE TITLE
(chore) Replace fetch with axios

### ISSUE THREAD

**Issue by nicarl** [opossum-tool/OpossumUI#503]
Currently we have some parts where we fetch data from external APIs with `fetch`. In https://github.com/opossum-tool/OpossumUI/pull/472 we started using axios (mostly because it handles error codes for you).

Known usages of `fetch`:
- `useFetchPackageInfo`

Do a search to find any other occurrences. Also look at https://github.com/opossum-tool/OpossumUI/pull/472 to see how requests can be mocked.

**Comment by benedikt-richter** [comment]
Fixed by #807
