### ISSUE TITLE
Multiple popup windows

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#759]
User can open multiple pop up windows (e.g. "Show Project Metadata") at the same time one above the others and have to close them one by one later.

**Comment by benedikt-richter** [comment]
In principle, this is a intended feature. It is, for example, used when the EDIT popup in REPORT view is open, data is modified and subsequently the CANCEL button is hit. In this case the UNSAVED CHANGES ppoup is opened on top of the EDIT popup.
Do you have specific use cases in mind where this should not be possible?

**Comment by vasily-pozdnyakov** [comment]
I think it is ok to open different popups one above other, but maybe it should not be possible to open multiple exactly the same popups (e.g. multiple press CTRL+F opens multiple search windows with exactly the same content).

**Comment by benedikt-richter** [comment]
Ok, I understand. That's a good point! That should not be allowed to happen.
