### ISSUE TITLE
Unknown version in windows app

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#776]
OpossumUI shows "unknown-version" of the app on Windows. For Mac version it seems to work fine.

![image](https://user-images.githubusercontent.com/85183359/175551224-a25e7373-e66e-4451-9cee-69f7a5aaeda1.png)

**Comment by leslielazzarino** [comment]
Low prio. Could not fix it quickly.

**Comment by someshkhandelia** [comment]
### Context

![image](https://user-images.githubusercontent.com/9270691/204745853-e3bd0da3-69c8-4eed-9046-3412abb0f952.png)

![image](https://user-images.githubusercontent.com/9270691/204746158-f33bba41-9c8b-4f92-a473-83e5a74123b7.png)

![image](https://user-images.githubusercontent.com/9270691/204746539-d10922b3-3dd2-4fcd-a083-e5745642aaba.png)

### Current question: 
How does `commitInfo` get `unknown-version` value ? (especially in windows and not mac)

**Comment by someshkhandelia** [comment]
The `commitInfo` file is in .gitignore. Therefore we cannot track its update  (git blame)

**Comment by someshkhandelia** [comment]
spoke with @leslielazzarino. It seems we need a way to introduce a version value in the windows command, just like we have in the linux command in `package.json`

`"update-commit-hash": "run-script-os"`

`"update-commit-hash:darwin:linux": "COMMIT_INFO=$(git describe --exact-match --tags 2> /dev/null || git rev-parse --short HEAD); echo \"{\\\"commitInfo\\\" : \\\"$COMMIT_INFO\\\" }\" > \"src/commitInfo.json\";\n"`

`"update-commit-hash:win32": "echo {\"commitInfo\" : \"unknown-version\" } > \"src\\commitInfo.json\""`
