### ISSUE TITLE
Introduce pie chart for critical licenses in signals in statistics popup

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#945]
The pie chart should display the number of signals as clustered by criticaliy: high, medium, or no criticality.

**Comment by benedikt-richter** [comment]
Consider refactoring the existing PieChart first, as suggested in https://github.com/opossum-tool/OpossumUI/pull/1016#issuecomment-1261834200

**Comment by someshkhandelia** [comment]
As part of https://github.com/opossum-tool/OpossumUI/pull/1053 the pie chart seems to have been extracted to a common component that can be reused across all future pie-charts (including the current issue).

**Comment by someshkhandelia** [comment]
**The current idea to implement the pie chart would be like a plugin. We just have to provide relevant data to the CustomizedPieChart component.:**
![image](https://user-images.githubusercontent.com/9270691/195042863-1954eb92-1b39-495d-81c8-cffd8d00dc10.png)


**The previous pie chart implementation used a function to create the data. We will also create a function in project-statistics-popup-helpers.ts to do the same.**
![image](https://user-images.githubusercontent.com/9270691/195043689-b3be68ff-e870-4b5f-8c7c-93723134696f.png)


**The data should be of the form (array of dictionaries):**
![image](https://user-images.githubusercontent.com/9270691/195044903-01e2ba12-c61a-4d4f-aae3-42193d837bd7.png)
![image](https://user-images.githubusercontent.com/9270691/195044651-6421adf7-f4f2-437e-9ae7-c3aede748eb6.png)


**This data is then visualised as:**
![image](https://user-images.githubusercontent.com/9270691/195045106-79d8c4eb-3f5c-4460-8063-957733e69d84.png)

**Comment by someshkhandelia** [comment]
Previously, the statistics popup looked like this:
![image](https://user-images.githubusercontent.com/9270691/195051664-07cadee6-5a21-4242-a820-470c6a90950e.png)

**Comment by someshkhandelia** [comment]
### Previously, the popup looked like this:
![image](https://user-images.githubusercontent.com/9270691/195051664-07cadee6-5a21-4242-a820-470c6a90950e.png)

### Now, the popup looks like this:
![image](https://user-images.githubusercontent.com/9270691/195113713-dea9d088-fadb-411f-8b6f-595034904eab.png)

![image](https://user-images.githubusercontent.com/9270691/195114172-673dd824-35b8-456d-9ce6-6e2e4a2686ac.png)

![image](https://user-images.githubusercontent.com/9270691/195114402-1e68dd28-968c-40c8-aa02-5d627fd22500.png)

![image](https://user-images.githubusercontent.com/9270691/195114652-041aac8a-fd2d-4b6e-8586-9d8f18bc56f0.png)
