### ISSUE TITLE
Replace pre-calculation of resourcesWithAttributedChildren

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#961]
`resourcesWithAttributedChildren` have been introduced in `AttributionData` back at the time when we were showing down-arrows for signals and attributions (and were not virtualizing the tree). This data it is not optimized for the folder colors, and expensive to compute. Therefore:
1. remove it
2. if tree navigation becomes slower add new pre-computed data, that is:
  2.1 optimized to get the folder color,
  2.2 can be updated with cheap (aka fast) calculation if an attribution is created/deleted or a signal is hidden.

**Comment by benedikt-richter** [comment]
As this ticket is unclear and also @vasily-pozdnyakov does not remember this scope/rationale, we close this issue.
