### ISSUE TITLE
Show percentage for signals in folder content

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#963]
As a user I want to get a quick overview of the percentage of files covered by a signal in the folder content.
Alternatively the total number might be sufficient.

Note: So far we do not use inference for signals (unlike we do for attributions). This seems to be necessary for this feature to make sense.

**Comment by benedikt-richter** [comment]
I agree with the "note"-part. To be able to provide a realistic picture of the number of files affected by a signal one would have to infer these down to all files that are affected by it.

**Comment by benedikt-richter** [comment]
Introducing inference for signals probably is very expensive, while the impact of this feature seems to be rather small. Closing it therefore.
