### ISSUE TITLE
Get rid of double scrollbars in Signals column

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#968]
As a user I do not want to have two scroll bars in the signals column. The result should satisfy the following goals:
- it should be easy to skip to another section of signals, e.g. jump to ScanCode
- if there are just a few signals, e.g. 4 from different sources for a file, they should all be visible at first glance
- If there are many signals, it should be easy to get an understanding of the "most common signals" over all sources

Ideas:
- A possible solution is to have - besides the accordions for signals, signals in folder content, and attributions in folder contents - accordions that contain the respective signals from different sources. These would initially be collapsed. If a user wants to look into one they have to expand the  respective source. This could remove the double scrollbar.
- Another idea would be to remove the accordions completely and put everything into a single virtual list (maybe with some way to quickly go to a certain section).
- A scroll trough accordeon would be the premium solution.

Now:
![image](https://user-images.githubusercontent.com/85183359/189623586-57e35d0e-e74a-4cf8-aafc-75bd0f746c90.png)

**Comment by mstykow** [comment]
Done already on some other task.
